name: Setup tools
description: Setup tools according to .tool-versions

runs:
  using: "composite"
  steps:
    - name: Gather asdf versions
      uses: endorama/asdf-parse-tool-versions@v1
      id: versions
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.versions.outputs.tools.terraform }}
        terraform_wrapper: false
    - name: Setup node (cf. https://github.com/hashicorp/setup-terraform/issues/84)
      uses: actions/setup-node@v4
      with:
        node-version: 16
